version: "3"
services:
  # WordPress(PHP7.2)
  wp:
    build: ./docker
    ports:
      - 80:80
    volumes:
      - ./wordpress/html:/var/www/html
    working_dir: "/var/www/html"
    tty: true
    depends_on:
      - mysql

  # MySQL
  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: blog_db
    volumes:
      - mysql-data:/var/lib/mysql

# named volume
volumes:
  mysql-data:
